### PR TITLE
DDCE-5502 Upgrade linter

### PR DESCRIPTION
**Pull request by gastonracui**

### CODE REVIEW

**Comment by lmugnai** [comment]
@gastonracui can we also add A11y/test to run all tests too please. Also, update readme file to inform users that these tests will be ran and an a11y report will be generated. Thanks

**Comment by lmugnai** [comment]
@gastonracui the following can be updated:

- com.fasterxml.jackson.module:jackson-module-scala : 2.17.0  -> 2.17.1                            
- uk.gov.hmrc.mongo:hmrc-mongo-play-30              : 1.8.0              -> 1.9.0                   
- uk.gov.hmrc.mongo:hmrc-mongo-test-play-30:test    : 1.8.0              -> 1.9.0                   
- uk.gov.hmrc:play-frontend-hmrc-play-30            : 8.5.0                       -> 9.10.0

**Comment by lmugnai** [comment]
@gastonracui we can remove the following from application.conf as they are provided by bootstrap:

- play.http.session.httpOnly=true
- play.http.session.secure=false
- play.http.session.cookieName="mdtp"

**Comment by gastonracui** [comment]
> @gastonracui the following can be updated:
> 
> * com.fasterxml.jackson.module:jackson-module-scala : 2.17.0  -> 2.17.1
> * uk.gov.hmrc.mongo:hmrc-mongo-play-30              : 1.8.0              -> 1.9.0
> * uk.gov.hmrc.mongo:hmrc-mongo-test-play-30:test    : 1.8.0              -> 1.9.0
> * uk.gov.hmrc:play-frontend-hmrc-play-30            : 8.5.0                       -> 9.10.0

Hi @lmugnai, for the play frontend update we have this ticket already: https://jira.tools.tax.service.gov.uk/browse/DDCE-5463

**Comment by gastonracui** [comment]
> @gastonracui can we also add A11y/test to run all tests too please. Also, update readme file to inform users that these tests will be ran and an a11y report will be generated. Thanks

@lmugnai its already there, but will add the README part, thanks!

**Review by lmugnai — APPROVED** [review]

**Pull request merged**
