### PR TITLE
DIT-2287 Add metrics collection to connectors

### PR DESCRIPTION
**Pull request by DavidGregory084**
This builds on #196, adding metrics collection to connectors.

### CODE REVIEW

**Review by periklas — APPROVED** [review]
👍

**Review by OC-Pomaroff — APPROVED** [review]
Looks good

**Comment by DavidGregory084** [comment]
Not sure what to make of the build failure, a test which uses the `DataCacheConnector` is failing but the test uses a mock of the `DataCacheConnector` so it's not using any changed code?

**Review by gorkemunsal — APPROVED** [review]
LGTM

**Pull request merged**
